<a href="https://colab.research.google.com/github/Yuu314/dap-2024/blob/main/les03/lab3res.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Лабораторная работа №3. NumPy**

**Подключение бибилиотеки NumPy**

In [1]:
import numpy as np
np.version.version

'2.0.2'

**Задание 1. Создать массив 10x10 со случайными значениями, найти минимум и максимум (низкая)**

In [18]:
random_array = np.random.randint(0, 101, (10, 10))
minimum = random_array.min()
maximum = random_array.max()
print("Массив 10x10:")
print(random_array)
print("\nМинимум:", minimum)
print("Максимум:", maximum)

Массив 10x10:
[[23 96 67  5 10 90 68 67 99 67]
 [41 34 16 16 26 27 22 63  4 63]
 [10 98 92 71 63 30 50 52  8 13]
 [46 54 43 44 59 57 76 29 97 80]
 [93 99 19 74 94 36 93 35 69 71]
 [59 50  1 38 50 96 84 89 42 75]
 [56 89 42 38 39 63  9 60 68  1]
 [ 8 89 79 92 96 52 52 24 87 96]
 [18 57 11 49 85 62 80 64 63 57]
 [73 82 14 38 58 69 25 46 30 85]]

Минимум: 1
Максимум: 99


**Задание 2. Создать 8x8 матрицу и заполнить её единицами и нулями в шахматном порядке**

In [19]:
chessboard = np.array([[ (i + j) % 2 for j in range(8)] for i in range(8)])
print("Матрица 8x8 в шахматном порядке:")
print(chessboard)


Матрица 8x8 в шахматном порядке:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


**Задание 3. Дан массив из 11 элементов, поменять знак у элементов, значения которых между 3 и 8**

In [32]:
arr = np.arange(11)
print(f'Исходная матрица: {arr}')
arr[(arr > 3) & (arr < 8)] *= -1
print(f'Изменённая матрица: {arr}')

Исходный массив: [ 0  1  2  3  4  5  6  7  8  9 10]
Изменённый массив: [ 0  1  2  3 -4 -5 -6 -7  8  9 10]


**Задание 4. Найти среднее заначение строки матрицы и вычесть его из каждого элемента строки**

In [41]:
matrix = np.random.randint(5, 10, (5, 5))
print(f'Исходная матрица: \n{matrix}')
avg = matrix.mean(axis=1, keepdims=True)
print(f'Среднеарифметические значения: \n{avg}')
new_matrix = matrix - avg
print(f'Измененная матрица: \n{new_matrix}')

Исходная матрица: 
[[9 5 8 7 9]
 [5 7 8 8 6]
 [9 5 7 9 8]
 [9 9 6 7 6]
 [7 6 5 9 7]]
Среднеарифметические значения: 
[[7.6]
 [6.8]
 [7.6]
 [7.4]
 [6.8]]
Измененная матрица: 
[[ 1.4 -2.6  0.4 -0.6  1.4]
 [-1.8  0.2  1.2  1.2 -0.8]
 [ 1.4 -2.6 -0.6  1.4  0.4]
 [ 1.6  1.6 -1.4 -0.4 -1.4]
 [ 0.2 -0.8 -1.8  2.2  0.2]]


**Задание 5. Поменяйте 1 и 2 строки матрицы**

In [42]:
matrix = np.arange(25).reshape(5,5)
print(f'Исходная матрица: \n{matrix}')
matrix[[0, 1]] = matrix[[1, 0]]
print(f'Матрица после обмена: \n{matrix}')

Исходня матрица: 
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
Матрица после обмена: 
[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


**Задание 6. Дан массив 10x2 подеставлющий собой точки в декартовой системе координат, преобразовать в полярную**

In [61]:
cartesian = np.random.randint(-10, 10, size=(10, 2))
print(f'Декартовы координаты:\n {cartesian}')

x = cartesian[:, 0]
y = cartesian[:, 1]
r = np.sqrt(x**2 + y**2)
theta = np.arctan2(y, x)

polar = np.column_stack((r, theta))
print(f'Полярные координаты:\n {polar}')

Декартовы координаты:
 [[ 6 -7]
 [ 1 -2]
 [ 7  8]
 [ 4 -3]
 [-5 -3]
 [ 5  4]
 [ 9 -4]
 [-8 -8]
 [-8 -6]
 [-5  8]]
Полярные координаты:
 [[ 9.21954446 -0.86217005]
 [ 2.23606798 -1.10714872]
 [10.63014581  0.85196633]
 [ 5.         -0.64350111]
 [ 5.83095189 -2.60117315]
 [ 6.40312424  0.67474094]
 [ 9.8488578  -0.41822433]
 [11.3137085  -2.35619449]
 [10.         -2.49809154]
 [ 9.43398113  2.12939564]]


**Задание 7. Заменить максимальный элемент массива на ноль**

In [49]:
arr = np.random.randint(1, 10, 5)
print(f'Исходный массив: {arr}')
max_index = np.argmax(arr)
arr[max_index] = 0
print(f'Изменённый массив: {arr}')

Исходный массив: [4 3 9 1 4]
Изменённый массив: [4 3 0 1 4]


**Задание 8. Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве. Добавление производиться только 1 раз**

In [60]:
size = 10
arr = np.random.randint(0, 100, size=size)
arr_index = np.random.choice(size, size=3, replace=False)
print(f'Исходный массив: {arr}')
print(f'Массив уникальных индексов: {arr_index}')
arr[arr_index] += 1
print(f'Массив после изменения: {arr}')

Исходный массив: [72 52 21  3 63 79 95 73 93 94]
Массив уникальных индексов: [7 8 2]
Массив после изменения: [72 52 22  3 63 79 95 74 94 94]


**Задание 9. Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением**

In [55]:
v = np.array([1, 2, 3, 4, 5])
print(f'Исходный вектор: {v}')
zeros = np.zeros(3)
new_v = np.array([])
for i in range(len(v)):
    new_v = np.append(new_v, v[i])
    if i < len(v) - 1:
        new_v = np.append(new_v, zeros)

print(f'Новый вектор: {new_v.astype(int)}')

Исходный вектор: [1 2 3 4 5]
Новый вектор: [1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


**Задание 10. Найти ближайшее к заданному значению число в заданном массиве**

In [52]:
arr = np.arange(100)
num = np.random.uniform(0,100)
print(f'Исходное чилсо: {num}')
print(f'Исходный массив: {arr}')
closest_index = np.argmin(np.abs(arr - num))
closest_value = arr[closest_index]
print(f'Ближайшее значение в массиве: {closest_value}')

Исходное чилсо: 38.54097955123341
Исходный массив: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
Ближайшее значение в массиве: 39


##**Контрольные вопросы:**
**1. Какой тип (dtype) будут иметь элементы массива?**
+ np.array([1, 4, 2, 5, 3]) - int64
+ np.array([1., 4, 2, 5, 3]) - float64
+ np.array([1, 4, 2, 5, 3], dtype='float128') - float128
+ np.array([1., 4, 2, 5, 3], dtype='complex128') - complex128
+ np.array([1, 4, 2, 5, 3], dtype ='float64') - float64
+ np.array([1, 4, 2, 5, 3], dtype =int64) - int64
+ np.array([1, 4, 2, 5, 3], dtype='bool') - bool
+ np.array([1, 4, 2, 5, 3], dtype='str') - U1 (или U2, в зависимости от длины строк)
+ np.array([1, 4, 2, 5, '3']) - U1 (или U2, так как есть строка)
+ np.array([1, -4, 2, 0, 1j]) - complex128

---

**2. Что будет выведено в консоль и почему?**
+ np.array([1, 4, 2, 5, 3], dtype='str')[1] + '1':
  + *Результат:* '41'
  + *Почему:* Элемент с индексом 1 это строка '4', конкатенация с '1' дает '41'
+ np.array([1, -4, 2, 0, 3], dtype='bool')[3] or np.array([1, -4, 2, 0, 3])[1]:
  + *Результат:* -4
  + *Почему:* dtype='bool' преобразует числа: 0 в False, остальные в True. Элемент с индексом 3 равен 0 → False. Операция or возвращает первый истинный операнд или последний.
+ np.array([1, -4, 2, 0, 3], dtype='bool')[3] and np.array([1, -4, 2, 0, 3])[1]:
  + *Результат:* False
  + *Почему:* Элемент с индексом 3 равен 0 → False. Операция and возвращает первый ложный операнд
+ np.array([1, -4, 2, 0, True], dtype='int64')[-1]:
  + *Результат:* 1
  + *Почему:* Так как True преобразуется в 1
+ np.array([1, -4, 2, 0, 1j], dtype='int64')[1]:
  + *Результат:* TypeError: int() argument must be a string, a bytes-like object or a real number, not 'complex'
  + *Почему:* Комплексное число 1j нельзя преобразовать в int64.
+ np.array([1, -4, 2, 0, 1j], dtype='str')[-1]:
  + *Результат:* '1j'
  + *Почему:* Комплексное число преобразуется в строку '1j'
+ np.array([1, 4, 2, 5, '3'])[-1] * 3:
  + *Результат:* '333'
  + *Почему:* Умножение строки: '3' * 3 = '333'

---

**3. Каков результат операции?**
+ np.ones((3, 5), dtype=float)
  + *Результат:* Матрица 3X5 заполненная 1.
+ np.full((3, 5), 3.14)
  + *Результат:* Матрица 3X5 заполненная 3.14
+ np.linspace(0, 1, 5)
  + *Результат:* Массив от 0 до 5 с равномерным шагом
+ np.diag((1,3,5))
  + *Результат:* Матрица 3X3 с 1,3,5 элементами на диагонали
+ np.smile((1,3,5))
  + *Результат:* AttributeError: module 'numpy' has no attribute 'smile'
+ np.random.random((3, 3))
  + *Результат:* Матрица 3X3 со случайными числами от 0 до 1
+ np.eye(3)
  + *Результат:*  Матрица 3X3 с 1 на диагонали и 0 в оставшихся элементах
+ np.empty(3)
  + *Результат:* Массив на 3 элемента с "мусорными" данными из памяти

---
**4. Дан двумерный массив X, что будет выведено в консоль?**

X = np.array([[3, 5, 2, 4], [7, 6, 8, 8], [1, 6, 7, 7]])
+ X[0,0] - 3(Элемент первой строки, первого столбца)
+ X[-1,-1] - 7(Элемент последней строки, последнего столбца)
+ X[0:1,-1] - 4(Первая строка, последний столбец)
+ X[0:2,-1] - [4, 8] (Первые две строки, последний столбец)
+ X[0:2,0:2] - [[3, 5], [7, 6]] (Первые две строки, первые два столбца)
+ X[1,1:3] - [6, 8] (Вторая строка, со 2-го по 3-й столбец (не включая 3-й индекс в Python))
+ X[1,:] - [7, 6, 8, 8] (Вся вторая строка)
+ X[:,:] - Весь массив
+ X[:] - Весь массив
+ X[::2,::2] - [[3, 2], [1, 7]] (Каждая вторая строка и каждый второй столбец)
+ X[0:3:2,0:3:2] - [[3, 2], [1, 7]]  (Строка с 0 по 3 с шагом 2, столбец с 0 по 3 с шагом 2)
+ X[::-1,::-1] - Обратный порядок массива по строкам и столбцам

---
**5. Дан двумерный массив grid, в чем различее между операциями?**

+ grid = np.arange(16).reshape((4, 4))
  + np.split(grid, [2]) -  Разделяет массив по строкам после индекса 2
  + np.split(grid, [2], axis=1) - Разделяет массив по столбцам после индекса 2

---
**6. В чем различие между операциями?**
+ [1, 2, 3] + [3, 2, 1] - конкатенация списков
+ np.array([1, 2, 3]) + np.array([3, 2, 1]) - поэлементное сложение массивов

---
**7. Как в CodeLab измерить время выполнения кода?**

В CodeLab (и в большинстве других Python-окружений) измерить время выполнения кода можно с помощью стандартных библиотек Python. Два самых распространённых способа:
+ Использование модуля time
+ Использование модуля timeit

---
**8. Дан массив X, каковы результаты операций?**

M = np.array([[3, 5, 2, 4],[7, 6, 8, 8],[1, 6, 7, 7]])
+ np.sum(M) - Сумма всех элементов матрицы(64)
+ np.sum(M, axis=1) - Сумма элементов по строкам (для каждой строки): ([14, 29, 21])
+ np.sum(M, axis=0) - Сумма элементов по столбцам (для каждого столбца): ([11, 17, 17, 19])
+ np.sum(M, axis=2) - AxisError: axis 2 is out of bounds for array of dimension 2
+ np.sum(M, 1) - Аналогично np.sum(X, axis=1): ([14, 29, 21])
+ sum(M) - Для многомерных массивов sum(X) суммирует по первой оси (аналогично np.sum(X, axis=0) для списков, но для NumPy массивов — по строкам): ([11, 17, 17, 19])
+ sum(M,1) - Встроенная функция sum не поддерживает аргумент axis.

---
**9. Дан массив X, что будет выведено в консоль?**

X = np.array([1,2,3,4])
+ X > 3 - Поэлементное сравнение: ([False, False, False,  True])
+ X < 3 - Поэлементное сравнение: ([ True,  True, False, False])
+ X[X < 3] - Возвращает элементы, для которых условие X < 3 истинно: ([1, 2])
+ X[X > 3] - Возвращает элементы, для которых условие X > 3 истинно:([4])
+ X[X != 3] - Возвращает элементы, для которых условие X != 3 истинно: ([1, 2, 4])

---
**10.  В чем преимущество массивов NumPy по сравнению с обычными списками. Чем обусловлено это преимущество?**
Массивы NumPy имеют несколько ключевых преимуществ перед обычными списками Python. Эти преимущества обусловлены особенностями реализации и оптимизации библиотеки NumPy.

*1. Скорость выполнения операций*
+ Преимущество: Операции с массивами NumPy выполняются значительно быстрее, чем с обычными списками Python, особенно при работе с большими объёмами данных.
+ Обоснование: NumPy написан на C и использует оптимизированные алгоритмы для работы с данными.
Операции над массивами NumPy вектор化ованы — они выполняются на уровне компилированного кода, без необходимости использовать циклы Python.
Списки Python — это динамические структуры данных, и операции с ними требуют дополнительных накладных расходов (например, проверка типов, динамическое изменение размера).


*2. Эффективное использование памяти*
+ Преимущество: Массивы NumPy занимают меньше памяти, чем списки Python, для хранения тех же данных.
+ Обоснование: NumPy хранит данные в непрерывном блоке памяти и использует фиксированные типы данных (например, int32, float64), что уменьшает накладные расходы.
Списки Python хранят ссылки на объекты, а не сами данные, что увеличивает расход памяти.


*3. Удобство работы с многомерными данными*
+ Преимущество: NumPy предоставляет удобные инструменты для работы с многомерными массивами (тензорами), что сложно или невозможно реализовать с помощью вложенных списков.
+ Обоснование: NumPy поддерживает многомерные массивы (например, матрицы, тензоры) и операции над ними (например, матричное умножение, транспонирование).
Операции над многомерными массивами выполняются эффективно и лаконично.


*4. Богатый функционал для математических операций*
+ Преимущество: NumPy предоставляет обширный набор математических функций (линейная алгебра, статистика, преобразования Фурье и др.), которые оптимизированы для работы с массивами.
+ Обоснование: Библиотека включает функции для векторных и матричных операций, что упрощает написание математического кода.
Например, умножение матриц, вычисление определителя, решение систем линейных уравнений и т. д.


*5. Интеграция с другими библиотеками*
+ Преимущество: NumPy является основой для многих научных библиотек Python (например, Pandas, SciPy, Matplotlib, scikit-learn), что делает его стандартом для научных вычислений.
+ Обоснование: Большинство библиотек для анализа данных и машинного обучения ожидают данные в формате NumPy-массивов.

In [115]:
X = np.array([1,2,3,4])
X[X != 3]

array([1, 2, 4])